function compile()

d = caps.path.dirname(caps.path.get_path());
compile_c(fullfile(d, '+particles', '+pse'), fullfile(d, '+particles', '+pse', 'applyPSE.cpp'));

end

function compile_c(outdir, filepath)
    if isunix
        eval(...
            sprintf([
                'mex CFLAGS="\\$CFLAGS -fopenmp  -std=c99" LDFLAGS="\\$LDFLAGS -fopenmp"'...
                ' -outdir %s %s'], ...
                outdir, filepath) ...
        )
    else
        % assume windows 
        eval(...
            sprintf([
                'mex COMPFLAGS="$COMPFLAGS /openmp /Za" LINKFLAGS="$LINKFLAGS"'...
                ' -outdir %s %s'], ...
                outdir, filepath) ...
        )
    end
end